import { defineConfig } from 'tsdown'

export default defineConfig({
  clean: true,
  deps: {
    alwaysBundle: ['figures', 'picocolors', 'ts-pattern'],
    onlyBundle: ['figures', 'is-unicode-supported', 'picocolors', 'ts-pattern'],
    onlyImport: ['ink', 'react'],
  },
  dts: true,
  fixedExtension: false,
  outDir: 'dist',
  entry: {
    index: 'src/index.ts',
    alert: 'src/display/alert.tsx',
    autocomplete: 'src/prompts/autocomplete.tsx',
    confirm: 'src/prompts/confirm.tsx',
    display: 'src/display/index.ts',
    'error-message': 'src/display/error-message.tsx',
    fullscreen: 'src/layout/fullscreen.tsx',
    'group-multi-select': 'src/prompts/group-multi-select.tsx',
    keys: 'src/keys.ts',
    interaction: 'src/interaction/index.ts',
    layout: 'src/layout/index.ts',
    'multi-select': 'src/prompts/multi-select.tsx',
    'password-input': 'src/prompts/password-input.tsx',
    'path-input': 'src/prompts/path-input.tsx',
    'progress-bar': 'src/display/progress-bar.tsx',
    prompts: 'src/prompts/index.ts',
    'scroll-area': 'src/layout/scroll-area.tsx',
    select: 'src/prompts/select.tsx',
    'select-key': 'src/prompts/select-key.tsx',
    spinner: 'src/display/spinner.tsx',
    'status-message': 'src/display/status-message.tsx',
    tabs: 'src/layout/tabs.tsx',
    'text-input': 'src/prompts/text-input.tsx',
    theme: 'src/theme.ts',
    'use-hotkey': 'src/use-key-binding.ts',
    'use-size': 'src/layout/use-size.tsx',
  },
  format: 'esm',
})
